services:
  token-manager:
    image: johannesschaefer/monitoring-token-manager:dev

  prometheus:
    image: johannesschaefer/monitoring-prometheus:dev
    ports:
      - "9090:9090"

  grafana:
    image: johannesschaefer/monitoring-grafana:dev
    ports:
      - "3001:3000"
